{
 "title": "Charging",
 "description": "Display recent Greta charging sessions",
 "tags": [
  "Greta",
  "MME"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Charging History",
   "type": "timeseries",
   "description": "Greta Charging History",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "query": "kwh_used = from(bucket: \"ev\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"charging\")\n  |> filter(fn: (r) => r._field == \"kwh_used\")\n  |> map(fn: (r) => ({ _time: r._time, \"kWh Used\": r._value }))\n  |> yield(name: \"kwh_used\")\n"
    },
    {
     "query": "kwh_added = from(bucket: \"ev\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"charging\")\n  |> filter(fn: (r) => r._field == \"kwh_added\")\n  |> map(fn: (r) => ({ _time: r._time, \"kWh Added\": r._value }))\n  |> yield(name: \"kwh_added\")"
    }
   ]
  },
  {
   "title": "Total Energy Added",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ev\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"charging\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kwh_added\")\n  |> drop(columns: [\"session\"])\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Total Energy Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ev\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"charging\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kwh_used\")\n  |> drop(columns: [\"session\"])\n  |> sum(column: \"_value\")"
    }
   ]
  },
  { "type": "welcome", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 } },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 15, "w": 12, "x": 0, "y": 11 } },
  { "title": "Latest from the blog", "type": "news", "gridPos": { "h": 15, "w": 12, "x": 12, "y": 11 } }
 ]
}